language: python
python:
 # - '3.4'
 # - '3.5'
 # - '3.6'
 - '3.7'

install: pip install -r requirements_travis.txt

script: python -m unittest discover
# script: python -m unittest tests/test_colored_logger.py
